"""Local images/<folder> name -> discography display name."""

ARTIST_DISPLAY = {
    "DArienzo": "Juan D'Arienzo",
    "Pugliese": "Osvaldo Pugliese",
    "DiSarli": "Carlos Di Sarli",
    "Biagi": "Rodolfo Biagi",
    "Calo": "Miguel Calo",
    "Laurenz": "Pedro Laurenz",
    "Tanturi": "Ricardo Tanturi",
    "Troilo": "Anibal Troilo",
    "Castillo": "Alberto Castillo",
    "Gardel": "Carlos Gardel",
    "Canaro": "Francisco Canaro",
    "Firpo": "Roberto Firpo",
    "Fresedo": "Osvaldo Fresedo",
    "DeCaro": "Julio De Caro",
    "Lomuto": "Francisco Lomuto",
    "Demare": "Lucio Demare",
    "DeAngelis": "Alfredo De Angelis",
    "Piazzolla": "Astor Piazzolla",
    "Basso": "José Basso",
    "Francini": "Enrique Francini",
    "DAgostino": "Angel D'Agostino",
    "Vargas": "Angel Vargas",
    "Rodriguez": "Enrique Rodriguez",
    "Donato": "Edgardo Donato",
    "Maglio": "Juan Maglio",
    "Maffia": "Pedro Maffia",
    "Carabelli": "Adolfo Carabelli",
    "Aieta": "Anselmo Aieta",
    "Cobian": "Juan Carlos Cobain",
    "OTVictor": "Orquesta Típica Victor",
    "Gobbi": "Alfredo Gobbi",
    "Pontier": "Armando Pontier",
    "FedericoDomingo": "Domingo Federico",
    "Maderna": "Osmar Maderna",
    "Varela": "Héctor Varela",
    "Salgan": "Horacio Salgan",
}
