"""Local images/<folder> name -> discography display name."""

ARTIST_DISPLAY = {
    "DArienzo": "Juan D'Arienzo",
    "Pugliese": "Osvaldo Pugliese",
    "DiSarli": "Carlos Di Sarli",
    "Biagi": "Rodolfo Biagi",
    "Calo": "Miguel Calo",
    "Laurenz": "Pedro Laurenz",
    "Tanturi": "Ricardo Tanturi",
    "Troilo": "Anibal Troilo",
    "Castillo": "Alberto Castillo",
    "Gardel": "Carlos Gardel",
    "Canaro": "Francisco Canaro",
    "Firpo": "Roberto Firpo",
    "Fresedo": "Osvaldo Fresedo",
    "DeCaro": "Julio De Caro",
    "Lomuto": "Francisco Lomuto",
    "Demare": "Lucio Demare",
    "DeAngelis": "Alfredo De Angelis",
    "Piazzolla": "Astor Piazzolla",
    "Basso": "José Basso",
    "Francini": "Enrique Francini",
    "DAgostino": "Angel D'Agostino",
    "Vargas": "Angel Vargas",
    "Rodriguez": "Enrique Rodriguez",
    "Donato": "Edgardo Donato",
    "Maglio": "Juan Maglio",
    "Maffia": "Pedro Maffia",
    "Carabelli": "Adolfo Carabelli",
    "Aieta": "Anselmo Aieta",
    "Cobian": "Juan Carlos Cobain",
    "OTVictor": "Orquesta Típica Victor",
    "Gobbi": "Alfredo Gobbi",
    "Pontier": "Armando Pontier",
    "FedericoDomingo": "Domingo Federico",
    "Maderna": "Osmar Maderna",
    "Varela": "Héctor Varela",
    "Salgan": "Horacio Salgan",
    "Corsini": "Ignacio Corsini",
    "Magaldi": "Agustín Magaldi",
    "Villoldo": "Angel Villoldo",
    "Greco": "Vicente Greco",
    "Quiroga": "Rosita Quiroga",
    "Delfino": "Enrique Delfino",
    "Rivero": "Edmundo Rivero",
    "Sassone": "Florindo Sassone",
    "SextetoMayor": "Sexteto Mayor",
    "Lamarque": "Libertad Lamarque",
    "ColorTango": "Color Tango",
    "Salamanca": "Fulvio Salamanca",
    "Omar": "Nelly Omar",
    "SanchezGorio": "Juan Sánchez Gorio",
    "OtrosAires": "Otros Aires",
    "SoloTango": "Solo Tango Orquesta",
    "Misteriosa": "Orquesta Tipica Misteriosa Buenos Aires",
    "Villarreal": "Juan Villarreal",
    "Bajofondo": "Bajofondo",
    "Ledesma": "Argentino Ledesma",
    "Romantica": "Orquesta Romantica Milonguera",
    "FedericoLeopoldo": "Leopoldo Federico",
    "GotanProject": "Gotan Project",
    "Cambareri": "Juan Cambareri",
    "Rotundo": "Francisco Rotundo",
    "CaloRoberto": "Roberto Caló",
    "Charlo": "Charlo",
    "Racciatti": "Donato Racciatti",
    "Mores": "Mariano Mores",
    "Diaz": "Hugo Díaz",
    "Merello": "Tita Merello",
    "Boero": "Ramiro Boero",
    "SansSouci": "Orquesta Tipica Sans Souci",
    "Simone": "Mercedes Simone",
    "Pizarro": "Manuel Pizarro",
    "ReyesDelTango": "Los Reyes del Tango",
    "SextetoCristal": "Sexteto Cristal",
    "SextetoMilonguero": "Sexteto Milonguero",
    "Pedevilla": "Ricardo Pedevilla",
    "Malerba": "Ricardo Malerba",
    "TangoBardo": "Tango Bardo",
    "LaJuanDArienzo": "La Juan D'Arienzo",
    "Villasboas": "Miguel Villasboas",
    "Andariega": "Orquesta Tipica Andariega",
    "SextetoTango": "Sexteto Tango",
    "SextetoFantasma": "Sexteto Fantasma",
    "PabloValle": "Pablo Valle Sexteto",
    "Tanghetto": "Tanghetto",
    "Narcotango": "Narcotango",
}
